### ISSUE TITLE
暂时发现的翻译错误

### ISSUE THREAD

**Issue by 0xtresser** [xiaoweiChen/CPP-17-STL-cookbook#2]
**前言** 
    	- 第三段，“并且，这样的使用时令人沮丧的”，“时”==》“是”？
    	- 第四段，“不使用C++所带的标准库，将会让C++看起来就像是具有类型的C语言”，“具有类型”==》“具有class类型”？
**关于本书**
    	- 适读群体，“如果你只想学习有关语言基础的只是”，“只是”==》？
**2.2**
    	- 最后一段，”好了，交换是无意义的，复盖是一种更好的方式。“，”复盖“==》？
**2.3** 
	- ##How it works...  md的二级标题效果没出来
**2.4**
	- 与2.3同样的问题
**2.5**
	- how to do it, "3.主函数中，我们否限定义了一个百万富翁的列表。", "否限"==》？
	- how to do it, "list<billionaire> billionaires {}", 最后少一个”；“？

**Comment by xiaoweiChen** [comment]
多谢勘误！
提到的问题已经在 92166479d6138286bd4c85b55bfd14e1bc06275c 提交中修复。
