### ISSUE TITLE
何时能出版中文版的实体书

### ISSUE THREAD

**Issue by akirakusen** [xiaoweiChen/CPP-17-STL-cookbook#6]
还是更喜欢看实体书，搜了一圈都没有...

**Comment by xiaoweiChen** [comment]
由于没有版权的原因，这个译版并不会正式出版。(主要是自己懒)
如果愿意看实体书可以下载原书，或者在release页面下载译版的pdf。然后，可以自行打印，或者找附近的印刷店进行印制和装订。当然，要是找不到复印店之类的地方，可以在某宝上找相应的店铺，对pdf进行印制和装订。

**Comment by xiaoweiChen** [comment]
忘记了，这本书没上传pdf。一会我上传一个，可供下载进行观看。

**Comment by xiaoweiChen** [comment]
pdf已经上传，如果需要可以去Release页面下载。
